version: "3.9"
services:
  app:
    container_name: next
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - type: bind
      source: ./next
      target: /usr/src/app
    command: sh -c "npm run dev"
    ports:
      - 3000:3000